"use client";

import { ArrowLeft, Check, ChevronRight, Clock3, CreditCard, LoaderCircle, MapPin, MessageSquareText, PackageCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import type { Order } from "@/lib/types";
import { price, t } from "@/lib/i18n";
import { useGroceryStore } from "@/store/grocery-store";

export function CheckoutScreen() {
  const { locale, cart, navigate, clearCart, order, setOrder } = useGroceryStore(); const c = t(locale); const items = Object.values(cart);
  const subtotal = items.reduce((sum, item) => sum + item.product.price * item.quantity, 0); const delivery = subtotal >= 35 ? 0 : 3.99; const [address, setAddress] = useState<string>(c.address); const [slot, setSlot] = useState(locale === "ru" ? "Сегодня, 19:00–20:00" : "Today, 7:00–8:00 PM"); const [comment, setComment] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function checkout(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ locale, address, slot, paymentLast4: "4242", comment, items: items.map((item) => ({ productId: item.product.id, quantity: item.quantity })) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setOrder(data as Order); clearCart(); } catch (err) { setError(err instanceof Error ? err.message : "Checkout failed"); } finally { setLoading(false); } }
  if (order) return <div className="screen order-success"><div className="success-mark"><Check size={32}/></div><span className="eyebrow">GROCERY COPILOT</span><h1>{c.confirmed}</h1><p>{c.confirmedBody}</p><div className="order-card"><div><PackageCheck/><span>{c.orderNumber}</span><strong>{order.id}</strong></div><div><Clock3/><span>{c.deliveryTime}</span><strong>{order.slot}</strong></div><div><MapPin/><span>{c.deliveryAddress}</span><strong>{order.address}</strong></div></div><button className="primary-button" onClick={() => { setOrder(undefined); navigate("home"); }}>{c.backHome}</button></div>;
  return <form className="screen checkout-screen" onSubmit={checkout}><header className="screen-header"><button type="button" className="icon-button" onClick={() => navigate("cart")}><ArrowLeft/></button><div><h1>{c.checkoutTitle}</h1><small>{items.length} {c.results}</small></div><span/></header>
    <div className="checkout-section"><label><span><MapPin size={19}/><b>{c.deliveryAddress}</b></span><input value={address} onChange={(event) => setAddress(event.target.value)} required minLength={6}/></label><label><span><Clock3 size={19}/><b>{c.deliveryTime}</b></span><select value={slot} onChange={(event) => setSlot(event.target.value)}><option>{locale === "ru" ? "Сегодня, 19:00–20:00" : "Today, 7:00–8:00 PM"}</option><option>{locale === "ru" ? "Сегодня, 20:00–21:00" : "Today, 8:00–9:00 PM"}</option><option>{locale === "ru" ? "Завтра, 09:00–10:00" : "Tomorrow, 9:00–10:00 AM"}</option></select><ChevronRight size={18}/></label><label><span><CreditCard size={19}/><b>{c.payment}</b></span><div className="fake-card"><i/>•••• 4242</div><ChevronRight size={18}/></label><label className="comment-field"><span><MessageSquareText size={19}/><b>{c.comment}</b></span><textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder={locale === "ru" ? "Например, позвонить в домофон" : "For example, call the intercom"}/></label></div>
    <div className="cart-summary checkout-summary"><div><span>{c.subtotal}</span><strong>{price(subtotal)}</strong></div><div><span>{c.deliveryFee}</span><strong>{delivery ? price(delivery) : c.free}</strong></div><div className="summary-total"><span>{c.total}</span><strong>{price(subtotal + delivery)}</strong></div></div>{error ? <p className="form-error">{error}</p> : null}<div className="sticky-action"><button className="primary-button" disabled={loading || !items.length}>{loading ? <LoaderCircle className="spin" size={18}/> : null}{c.placeOrder}<span>{price(subtotal + delivery)}</span></button></div>
  </form>;
}
